# Generated by Django 3.2.6 on 2021-08-12 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.UUIDField(editable=False)),
                ('data', models.JSONField(default={})),
            ],
        ),
    ]
